### ISSUE TITLE
Error on Instance Log

### ISSUE THREAD

**Issue by Crosus97** [frizzant/league-of-legends-rankify#5]
I get this error, on a Sinusbot docker

2020/03/19 15:05:56 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:288:48] Error: 403 Forbidden
2020/03/19 15:05:56 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: An Unknown Error Occurred. var level is not a number.
2020/03/19 15:05:56 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: undefined
2020/03/19 15:05:56 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: 
2020/03/19 15:05:56 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:292:48] Error: An Unknown Error Occurred. var level is not a number.
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: [object Object]
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:268:48] Error: 403 Forbidden
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: TypeError: Cannot read property '0' of undefined
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: 
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:286:48] Error: TypeError: Cannot read property '0' of undefined
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: [object Object]
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:288:48] Error: 403 Forbidden
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: An Unknown Error Occurred. var level is not a number.
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: undefined
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN Unhandled rejected promise: 
2020/03/19 15:05:57 6b4a3482 9ce69f0d PLUGIN [     lol-rankify:292:48] Error: An Unknown Error Occurred. var level is not a number.
![image](https://user-images.githubusercontent.com/46854222/77082352-3c25b280-69fc-11ea-875d-1a814bec491e.png)

![Sin título](https://user-images.githubusercontent.com/46854222/77082710-c1a96280-69fc-11ea-8215-774ce41412d6.png)

![image](https://user-images.githubusercontent.com/46854222/77082280-24e6c500-69fc-11ea-9cda-626a5f58b1df.png)

TY After all

And sorry if the problem its maded by me

anyhelp

**Comment by Crosus97** [comment]
#2 seems to be similar

**Comment by frizzant** [comment]
Correct. Thanks for all the info.
All others reported that the bug disappeared - So I am confused.

I will have to dig into that.

**Comment by frizzant** [comment]
If you leave me your server ip so i can come online and check that would be nice.
You can do it private/ or via sinusbot forums if you want to.

**Comment by Crosus97** [comment]
ok, i will create i will taltk to u to private

**Comment by Crosus97** [comment]
sinusbot better

**Comment by Crosus97** [comment]
> You can do it private/ or via sinusbot forums if you want to.

Pm on Sinusbot forum

**Comment by frizzant** [comment]
**403 (Forbidden)** This error indicates that the server understood the request but refuses to authorize it. There is no distinction made between an invalid path or invalid authorization credentials (e.g., an API key). The client should not continue to make similar requests.

Common Reasons

An invalid API key was provided with the API request.
A blacklisted API key was provided with the API request.
The API request was for an incorrect or unsupported path.

Can you please confirm this?
